import {StyleSheet, Platform} from 'react-native';

export default StyleSheet.create({
  containerSelect: {
    flex: 1,
    marginHorizontal: 4,
    paddingBottom: 0,
  },
  container: {
    flex: 1,
    marginHorizontal: 4,
    paddingBottom: 12,
  },
  fit: {
    marginLeft: 20,
    marginRight: 20,
  },
  above: {
    zIndex: 2000,
  },
  rechercheTextInput: {
    marginLeft: 20,
    flex: 1,
  },
  input: {
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 10,
    marginBottom: 5,
    borderRadius: 4,
    height: 50,
    fontFamily: 'Arial',
  },
  label: {
    fontSize: 16,
    fontWeight: 'normal',
    color: '#828282',
    fontFamily: 'Arial',
  },
  title: {
    fontSize: 16,
    fontWeight: 'normal',
    color: 'black',
    fontFamily: 'Arial',
  },
  normalTitle: {
    marginRight: 20,
    marginLeft: 20,
    fontSize: 16,
    fontWeight: 'normal',
    color: 'black',
    fontFamily: 'Arial',
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
    fontFamily: 'Arial',
  },
  mainTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: 'rgba(15, 87, 158, 1)',
    marginTop: 24,
    marginBottom: 8,
    fontFamily: 'Arial',
  },
  secondTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
    height: 50,
    lineHeight: 50,
    fontFamily: 'Arial',
  },
  labelTitleBlue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0088CC',
    height: 50,
    lineHeight: 50,
    fontFamily: 'Arial',
  },
  labelTitleBlueLhs: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0088CC',
    height: 24,
    lineHeight: 24,
    fontFamily: 'Arial',
  },
  titleSkin24: {
    color: '#333333',
    fontSize: 24,
    fontWeight: '400',
    marginVertical: 20,
    lineHeight: 31,
    fontFamily: 'Arial',
  },
  thirdTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000',
    fontFamily: 'Arial',
  },
  fourthTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#000',
    lineHeight: 26,
    fontFamily: 'Arial',
  },
  titleGreen: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1D5C42',
    fontFamily: 'Arial',
  },
  titleGreenCenter: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1D5C42',
    textAlign: 'center',
    fontFamily: 'Arial',
  },
  titleGreen14: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1D5C42',
    fontFamily: 'Arial',
  },
  titleGreen16: {
    color: '#1e5e37',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Arial',
  },
  titleGreen11: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1D5C42',
    fontFamily: 'Arial',
  },
  paragraph: {
    fontSize: 16,
    fontWeight: '400',
    color: '#000',
    marginVertical: 16,
    fontFamily: 'Arial',
  },
  paragraph14: {
    fontSize: 14,
    fontWeight: '400',
    color: '#000',
    marginVertical: 8,
    fontFamily: 'Arial',
  },
  link: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Arial',
    color: '#58A618',
    marginVertical: 16,
  },
  error: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Arial',
    color: '#F00',
  },
  linkblue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F579E',
    marginVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#0F579E',
    fontFamily: 'Arial',
  },
  linkUnderline: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Arial',
    color: '#0088CC',
    marginVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#0088CC',
  },
  customLabel: {
    minWidth: 280,
    color: '#0088CC',
    fontSize: 32,
    fontFamily: 'Arial',
    fontWeight: '400',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    marginBottom: 30,
    marginHorizontal: 'auto',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    shadowColor: '#338554',
    shadowOffset: {
      width: 1,
      height: 8,
    },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    textTransform: 'uppercase',
    textAlign: 'center',
    zIndex: 11,
  },
  validate: {
    backgroundColor: '#23a4ea',
    minWidth: 140,
    shadowOffset: {width: 2, height: 6},
    shadowColor: '#338554',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 4,
  },
  inValidate: {
    width: 140,
    backgroundColor: 'gray',
    fontFamily: 'Arial',
    color: 'black',
  },
  textError: {
    color: '#f00',
    fontSize: 14,
    fontFamily: 'Arial',
  },
  appButtonContainer: {
    flex: 1,
    backgroundColor: '#338554',
    flexDirection: 'row',
    marginBottom: 10,
    marginTop: 10,
    paddingHorizontal: 0,
    marginHorizontal: Platform.OS === 'web' ? 18 : 0,
    color: '#fff',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 50,
    maxHeight: 50,
    shadowOffset: {width: 2, height: 6},
    shadowColor: '#338554',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 4,
  },
  appButtonContainerBtn: {
    minWidth: 120,
    margin: 15,
    color: '#fff',
    padding: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    height: 50,
  },
  btnLayout: {
    flex: 1,
    minWidth: 140,
    justifyContent: 'center',
  },
});
