import {Dimensions, Platform, StyleSheet} from 'react-native';

const windowDim = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export const formsStyles = StyleSheet.create({
  visualFormTwoColumnPositionL: {
    minHeight: Platform.OS === 'web' ? 65 : 50,
  },
  visualFormTwoColumnPositionR: {
    minHeight: Platform.OS === 'web' ? 82 : 60,
  },
  visualFormTwoColumn: {
    backgroundColor: 'white',
    minHeight: Platform.OS === 'web' ? 65 : 50,
    paddingVertical: 16,
    paddingHorizontal: 13,
    // marginVertical: 10,
    marginVertical: Platform.OS === 'web' ? 16 : 0,
    marginHorizontal: 0,
    borderRadius: 8,
    shadowOffset: {width: 2, height: 6},
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    marginTop: 20,
    padding: 20,
  },
  containerHeader: {
    flex: 1,
    paddingTop: Platform.OS === 'web' ? 0 : 20,
  },
  formContainFull: {
    width: '100%',
    backgroundColor: 'white',
  },
  webformContainFull: {
    width: '100%',
  },
  webformContain: {
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    alignContent: 'center',
    alignItems: 'center',
    marginBottom: Platform.OS === 'web' ? 0 : '25%',
    flex: 1,
  },
  webformContainContract: {
    display: 'flex',
    flex: 1,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: Platform.OS === 'web' ? 0 : 0,
  },
  formContain: {
    // paddingTop: Platform.OS === 'web' ? 48 : 16,
    paddingBottom: Platform.OS === 'web' ? 48 : 16,
    // paddingRight: 16,
    width: '100%',
    borderRadius: Platform.OS === 'web' ? 10 : 0,
    minHeight: windowHeight * 1,
    justifyContent: 'flex-start',
  },
  formContainWithoutSidebar: {
    paddingTop: Platform.OS === 'web' ? 48 : 16,
    paddingBottom: Platform.OS === 'web' ? 48 : 16,
    paddingRight: Platform.OS === 'web' ? windowDim * 0.02 : 16,
    width: '100%',
    borderRadius: Platform.OS === 'web' ? 10 : 0,
    minHeight: windowHeight * 1,
    paddingLeft: 16,
  },
  realFlex: {
    flex: Platform.OS === 'web' ? 1 : 0,
  },
  formContainPayment: {
    paddingTop: Platform.OS === 'web' ? 0 : 5,
    paddingBottom: Platform.OS === 'web' ? 48 : 16,
    paddingHorizontal: Platform.OS === 'web' ? 40 : 20,
    backgroundColor: '#fff',
    maxWidth: Platform.OS === 'web' ? 1025 : '100%',
    width: '100%',
    borderRadius: Platform.OS === 'web' ? 10 : 0,
    minHeight: windowHeight - 75,
  },
  webformContainChat: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'center',
    marginVertical: Platform.OS === 'web' ? 40 : 0,
    flex: 1,
    height: Platform.OS === 'web' ? windowHeight - 75 : '100%',
  },

  formContainChat: {
    height: Platform.OS === 'web' ? windowHeight - 75 : '100%',
    paddingTop: Platform.OS === 'web' ? 48 : 5,
    paddingBottom: Platform.OS === 'web' ? 48 : 16,
    paddingHorizontal: Platform.OS === 'web' ? 80 : 20,
    backgroundColor: '#fff',
    maxWidth: Platform.OS === 'web' ? 1025 : '100%',
    width: '100%',
    borderRadius: Platform.OS === 'web' ? 10 : 0,
    minHeight: windowHeight - 75,
  },
  bgTrans: {
    backgroundColor: 'transparent',
  },
  formWebs: {
    maxWidth: 640,
  },
  fondUnlogged: {
    resizeMode: 'cover',
  },
  formGroup: {
    paddingVertical: 16,
  },
  labelStyle: {
    color: '#4f4f4f',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 10,
    marginBottom: 5,
  },
  itemSearchStyle: {
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 1)',
    borderRadius: 30,
    backgroundColor: '#fff',
    flexDirection: 'row',
    marginRight: 20,
    marginTop: 16,
    marginBottom: 5,
    marginLeft: 20,
    height: 50,
  },
  itemSearchIcone: {
    marginLeft: 15,
    marginTop: 15,
    width: 20,
    height: 20,
  },
  itemSearchIconeDetailContract: {
    marginLeft: 15,
    marginTop: 50,
    width: 20,
    height: 20,
  },
  itemSearchIconeContract: {
    marginLeft: 15,
    marginTop: 15,
    width: 20,
    height: 20,
    right: 90,
    display: 'flex',
  },
  itemSearchInput: {
    marginLeft: 20,
    flex: 1,
  },
  itemInputStyle: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 4,
    color: '#000',
    fontSize: 14,
    flexDirection: 'row',
    textAlignVertical: 'center',
    paddingHorizontal: 0,
    height: 50,
  },
  itemInputStyleTextArea: {
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 1)',
    borderRadius: 4,
    backgroundColor: '#fff',
    color: '#000',
    fontSize: 14,
    flexDirection: 'row',
    marginTop: 10,
    paddingTop: 10,
    paddingLeft: 16,
    marginBottom: 16,
    height: 200,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    fontFamily: 'Arial',
  },
  itemSelectStyle: {
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 1)',
    fontSize: 14,
    backgroundColor: '#fff',
    height: 50,
    marginBottom: 16,
    marginTop: 5,
    fontFamily: 'Arial',
  },
  itemSelectPickerStyle: {
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 1)',
    paddingLeft: 16,
    paddingRight: 16,
    width: '100%',
    height: 50,
    borderRadius: 4,
  },
  itemTextAreaStyle: {
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 1)',
    borderRadius: 25,
    backgroundColor: '#fff',
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 20,
    height: 150,
    color: '#fff',
  },
  containerResponse: {
    marginVertical: 16,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    paddingVertical: 8,
  },
  cornerResponse: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    borderColor: 'rgba(240, 244, 248, 0.875)',
    borderWidth: 1,
    maxWidth: 395,
  },
  cornerInResponse: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderRadius: 16,
    borderColor: 'rgba(0, 0, 0, 1)',
    borderWidth: 1,
    maxWidth: 395,
    backgroundColor: 'rgba(255, 255, 255, 0.875)',
  },
  txtBlack: {
    color: 'rgba(29, 92, 66, 1)',
    fontSize: 32,
    fontWeight: '400',
    fontFamily: 'Arial',
  },
  txtGreen: {
    color: 'rgba(29, 92, 66, 1)',
    fontSize: 32,
    fontWeight: '700',
    fontFamily: 'Arial',
  },
  inputError: {
    borderColor: '#f00',
  },
  imagesLink: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  line: {
    flex: 1,
    borderBottomColor: '#e0e0e0',
    borderBottomWidth: 1,
    marginHorizontal: 10,
  },
  formLogInscr: {
    backgroundColor: '#fff',
    position: 'relative',
    flex: 1,
  },
  FondMobile: {
    width: windowDim / 2.1,
    height: windowHeight / 3,
    resizeMode: 'contain',
    position: 'absolute',
    right: -20,
    top: -5,
  },
  profilInscOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: 'hidden',
  },
  profilInsc: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  profilForm: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
  },
  profilFormInput: {
    backgroundColor: 'rgba(240, 244, 248, 0.875)',
    borderRadius: 30,
    color: '#000',
    fontSize: 14,
    flexDirection: 'row',
    fontWeight: '700',
    marginTop: 5,
    paddingLeft: 16,
    marginBottom: 16,
    height: 50,
    fontFamily: 'Arial',
  },
  profilFormInputEditable: {
    backgroundColor: '#ffffff',
    borderRadius: 30,
    borderColor: '#E0E0E0',
    borderWidth: 1,
    borderStyle: 'solid',
    color: '#000',
    fontSize: 14,
    flexDirection: 'row',
    fontWeight: '700',
    marginTop: 5,
    paddingLeft: 16,
    marginBottom: 16,
    height: 50,
    fontFamily: 'Arial',
  },
  autoComplete: {
    borderWidth: 1,
    borderColor: 'rgba(224, 224, 224, 1)',
    borderRadius: 12,
    backgroundColor: '#fff',
    color: '#000',
    fontSize: 14,
    flexDirection: 'column',
    padding: 16,
    marginBottom: 16,
    fontFamily: 'Arial',
  },
  autoCompleteTxt: {
    backgroundColor: '#fff',
    fontSize: 14,
    paddingHorizontal: 16,
    paddingVertical: 4,
    fontFamily: 'Arial',
  },
  iconEye: {
    height: 17,
    width: 23,
    marginLeft: 18,
    marginTop: 13,
  },
  dateIcon: {
    height: 22,
    width: 20,
    marginLeft: 283,
    // marginTop: 2,
  },
  formContainContract: {
    paddingTop: Platform.OS === 'web' ? 48 : 5,
    paddingBottom: Platform.OS === 'web' ? 48 : 16,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    maxWidth: Platform.OS === 'web' ? '100%' : 1025,
    // width: '100%',
    borderRadius: Platform.OS === 'web' ? 10 : 0,
    minHeight: windowHeight - 75,
  },
  contractWrapper: {
    width: 'calc(100% - 24px)',
    maxWidth: 768,
    marginHorizontal: 16,
  },
  paymentContain: {
    minHeight: windowHeight - 80,
    backgroundColor: '#fff',
  },
  paymentContainWeb: {
    minHeight: windowHeight - 80,
    backgroundColor: 'rgb(255, 255, 255)',
  },
  rowFlex: {
    display: 'flex',
    flexWrap: 'nowrap',
    flexDirection: 'row',
  },
  columnFlex: {
    display: 'flex',
    flexWrap: 'nowrap',
    flexDirection: 'column',
  },
  switchContainer: {
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    minHeight: 50,
    marginVertical: 10,
  },
});
