import {Dimensions, Platform, StyleSheet} from 'react-native';

let windowDim = Dimensions.get('window').width;
// const test = () => {
//   if (windowDim <= 1024) return 'red';
//   else return 'blue';
// };
export const reloadStyles = () => {
  windowDim = Dimensions.get('window').width;
  const gs = StyleSheet.create({
    /* mobile */
    mobileContainerFluid: {
      padding: 8,
      overflow: 'visible',
    },
    /* WEB */
    containerFluid: {
      alignSelf: 'center',
      marginLeft: 'auto',
      marginRight: 'auto',
      // width: '100%',
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 16,
      // backgroundColor:  test(),
      flex: 1,
      maxWidth: windowDim <= 1024 ? '100%' : 960,
    },
    containerFluidHeader: {
      justifyContent: 'flex-start',
      alignSelf: 'center',
      marginLeft: 'auto',
      marginRight: 'auto',
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 16,
      flex: 1,
      // maxWidth: windowDim <= 1024 ? '100%' : 960,
      maxWidth: '100%',
      position: 'relative',
    },
    formContain: {
      paddingTop: Platform.OS === 'web' ? 48 : 5,
      paddingBottom: Platform.OS === 'web' ? 48 : 16,
      paddingHorizontal: windowDim <= 786 ? 20 : 100,
    },
    row: {
      flex: 1,
      width: '100%',
      flexDirection: 'row',
      flexWrap: 'wrap',
      overflow: 'visible',
    },
    dHorizontal: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      alignContent: 'center',
      paddingVertical: 16,
      paddingHorizontal: 8,
      flexWrap: 'nowrap',
    },
    containerMenuItem: {
      height: 156,
      marginTop: 12,
      marginRight: 12,
      marginLeft: 12,
      marginBottom: 12,
      paddingRight: windowDim <= 320 ? 12 : 24,
      paddingLeft: windowDim <= 320 ? 12 : 24,
      paddingTop: windowDim <= 320 ? 12 : 24,
      paddingBottom: windowDim <= 320 ? 12 : 24,
      flexBasis: windowDim <= 725 ? 'calc(50% - 24px)' : 'calc(25% - 24px)',
      minWidth: windowDim <= 320 ? 'calc(100% - 24px)' : 'calc(25% - 24px)',
      // maxWidth: 'calc(50% - 24px)',
      backgroundColor: 'white',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'flex-start',
      flex: 1,
      shadowOffset: {width: 2, height: 6},
      shadowColor: '#000000',
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 4,
    },
    containerMenuItemFullHome: {
      marginTop: 12,
      marginRight: 12,
      marginLeft: 12,
      marginBottom: 12,
      paddingLeft: windowDim <= 576 ? 0 : 0,
      paddingRight: windowDim <= 576 ? 0 : 0,
      paddingTop: windowDim <= 576 ? 0 : 0,
      paddingBottom: windowDim <= 576 ? 0 : 0,
      backgroundColor: 'rgba(255,255,255,0)',
      borderRadius: 16,
      borderColor: '#f2f5f6',
      alignItems: 'center',
      justifyContent: 'flex-start',
      flexDirection: 'row',
      flex: 2,
      flexBasis: windowDim <= 720 ? 'calc(100% - 24px)' : 'calc(50% - 24px)',
      maxWidth: windowDim <= 1024 ? 'calc(100% - 24px)' : 'calc(50% - 24px)',
      shadowOffset: {width: 2, height: 6},
      shadowColor: '#000000',
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 4,
    },
    containerMenuItemFull: {
      marginTop: 12,
      marginRight: 12,
      marginLeft: 12,
      marginBottom: 12,
      paddingLeft: windowDim <= 576 ? 16 : 24,
      paddingRight: windowDim <= 576 ? 16 : 24,
      paddingTop: windowDim <= 576 ? 16 : 32,
      paddingBottom: windowDim <= 576 ? 16 : 32,
      borderRadius: 16,
      borderColor: '#f2f5f6',
      alignItems: 'center',
      justifyContent: 'flex-start',
      flexDirection: 'row',
      flex: 2,
      flexBasis: windowDim <= 720 ? 'calc(100% - 24px)' : 'calc(50% - 24px)',
      maxWidth: windowDim <= 1024 ? 'calc(100% - 24px)' : 'calc(50% - 24px)',
      shadowOffset: {width: 2, height: 6},
      shadowColor: '#000000',
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 4,
    },
    MenuItemFont: {
      marginTop: 8,
      marginBottom: 8,
      fontSize: 16,
      lineHeight: 20,
      textAlign: 'center',
      justifyContent: 'center',
      fontWeight: '400',
      fontFamily: 'Arial',
    },
    MenuItemLogo: {
      marginTop: 8,
      width: 64,
      height: 64,
      resizeMode: 'contain',
      display: 'flex',
      minHeight: 60,
    },
    MenuIteAvatarContain: {
      width: 64,
      height: 64,
      borderRadius: 64,
      overflow: 'hidden',
    },
    MenuItemLogoFull: {
      width: 64,
      height: 64,
      borderRadius: 64,
      resizeMode: 'contain',
    },
    profilText: {
      marginLeft: windowDim <= 576 ? 16 : 24,
      marginTop: 8,
      marginBottom: 8,
      flex: 1,
    },

    /* ALL */
    titleSecondaryH2: {
      fontSize: 16,
      color: '#FFFFFF',
      fontWeight: 'bold',
      marginBottom: windowDim <= 720 ? 4 : 8,
      fontFamily: 'Arial',
    },
    titlePrimaryH2: {
      fontSize: windowDim <= 720 ? 18 : 16,
      lineHeight: 21,
      color: '#1D5C42',
      fontWeight: '700',
      marginTop: windowDim <= 720 ? 0 : 4,
      marginBottom: windowDim <= 720 ? 8 : 12,
      fontFamily: 'Arial',
    },
    paragraphe: {
      fontSize: windowDim <= 1024 ? 12 : 16,
      lineHeight: 18,
      fontWeight: '400',
      marginTop: windowDim <= 720 ? 4 : 8,
      marginBottom: windowDim <= 720 ? 12 : 16,
      fontFamily: 'Arial',
    },
    link: {
      color: '#58A618',
      fontSize: 12,
      fontWeight: 'bold',
      textDecorationLine: 'underline',
      fontFamily: 'Arial',
    },
    linkProfil: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
      textDecorationLine: 'underline',
      fontFamily: 'Arial',
    },
    colorLightPrimary: {
      color: '#9DB6AC',
    },
    imageIcon: {
      width: 24,
      height: 24,
      resizeMode: 'contain',
      marginVertical: 16,
      marginLeft: 24,
      marginRight: 8,
    },
    linearGradient: {
      flex: 1,
      paddingLeft: 15,
      paddingRight: 15,
      borderRadius: 5,
    },
    textDescription: {
      fontSize: windowDim <= 1024 ? 12 : 16,
      lineHeight: 18,
      fontWeight: '400',
      marginTop: windowDim <= 720 ? 4 : 8,
      marginBottom: windowDim <= 720 ? 12 : 16,
      color: '#A0CDA2',
    },
    fullEcranWeb: {
      width: '100%',
    },
    otherMenu: {
      backgroundColor: 'rgba(255, 255, 255, .08)',
      height: 56,
      borderRadius: 8,
      marginHorizontal: 10,
      marginTop: 16,
      marginBottom: 16,
      paddingLeft: 0,
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      shadowColor: '#fff',
      shadowOffset: {
        width: 4,
        height: 2,
      },
      shadowOpacity: 0.001,
      shadowRadius: 20,
      elevation: 2,
    },
    iconOtherMenu: {
      width: 24,
      height: 24,
      marginLeft: 20,
    },
    textOtherMenu: {
      color: '#fff',
      fontWeight: '700',
      lineHeight: 56,
      marginLeft: 10,
      fontFamily: 'Arial',
    },
    boxTopGraphic: {
      padding: 16,
      flexDirection: 'column',
      borderRadius: 8,
      shadowColor: 'rgba(51, 133, 84, 0.1)',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      // shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 6,
      zIndex: 10,
    },
    boxGraphic: {
      // paddingVertical: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginHorizontal: 4,
      marginTop: 30,
      backgroundColor: '#ffffff',
      paddingVertical: 20,
      paddingHorizontal: 20,
      borderRadius: 8,
      shadowColor: 'rgba(51, 133, 84, 0.1)',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      // shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 6,
      zIndex: 10,
    },
    boxGraphicMobile: {
      // paddingVertical: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginHorizontal: 4,
      marginTop: 14,
      backgroundColor: '#ffffff',
      paddingVertical: 4,
      paddingHorizontal: 4,
      borderRadius: 8,
      shadowColor: 'rgba(51, 133, 84, 0.1)',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      // shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 6,
      zIndex: 10,
    },
  });
  return gs;
};

export const globalStyle = reloadStyles();

export default globalStyle;
