export default {
  app: require('../assets/icons/app.png'),
  currency: require('../assets/icons/currency.png'),
  langue: require('../assets/icons/langue.png'),
  stroke3: require('../assets/icons/stroke3.png'),
  stroke1: require('../assets/icons/stroke1.png'),
  airbnb: require('../assets/logo/airbnb.png'),
  fedEx: require('../assets/logo/fedEx.png'),
  google: require('../assets/logo/google.png'),
  hubspot: require('../assets/logo/hubspot.png'),
  microsoft: require('../assets/logo/microsoft.png'),
  icon_description: require('../assets/icons/icon_description.png'),
  path1: require('../assets/icons/path1.png'),
  path: require('../assets/icons/path.png'),
  social: require('../assets/icons/social.png'),
  twits: require('../assets/icons/path1.png'),
  user: require('../assets/icons/user.png'),
  home: require('../assets/icons/home.png'),
  search: require('../assets/icons/search.png'),
  like: require('../assets/icons/like.png'),
  back: require('../assets/icons/back.png'),
  point_interest: require('../assets/icons/point-of-interest.png'),
  demande: require('../assets/icons/demande.png'),
  offre_watch: require('../assets/icons/offre_watch.png'),
  setting_set: require('../assets/icons/setting_set.png'),
  icons_status: require('../assets/icons/icons_status.png'),
  imagespay: require('../assets/icons/imagespay.png'),
  invitefriends: require('../assets/icons/invitefriends.png'),
  prestataire: require('../assets/icons/prestataire.png'),
  help: require('../assets/icons/help.png'),
  logout: require('../assets/icons/logout.png'),
  login: require('../assets/icons/login.png'),
  close: require('../assets/icons/close.png'),
  star: require('../assets/icons/star.png'),
  ok: require('../assets/icons/ok-icon.png'),
  // icowish: require('../assets/icons/icowish.png'),
};
