import {Platform, StyleSheet} from 'react-native';

export default StyleSheet.create({
  popContainer: {
    height: 'calc(100vh - 200px)',
    maxWidth: 500,
    //flex: 1,
    justifyContent: 'flex-start',
    alignSelf: 'center',
    backgroundColor: 'white',
    borderRadius: 20,
  },
  bkgPop: {
    backgroundColor: '#172D59',
    padding: 0,
    overflow: 'scroll',
    maxHeight: 'calc(100vh - 180px)',
  },
  oddInfo: {
    backgroundColor: '#e9ecef',
    minHeight: 50,
    lineHeight: 24,
    fontSize: 16,
    fontFamily: 'Poppins',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: 16,
    textTransform: 'uppercase',
  },
  evenInfo: {
    backgroundColor: '#ffffff',
    minHeight: 50,
    lineHeight: 24,
    fontSize: 16,
    fontFamily: 'Poppins',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: 16,
    textTransform: 'uppercase',
  },
  labelInfos: {
    textTransform: 'none',
    fontWeight: 'bold',
    flexBasis: '50%',
  },
  meatipContainer: {
    right: 0,
    backgroundColor: 'rgba(23, 45, 89, 0.15)',
    maxWidth: 400,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Platform.select({web: 50, native: 20}),
    paddingVertical: Platform.select({web: 0, native: 15}),
    minHeight: 64,
    borderRadius: 5,
    position: 'relative',
    alignSelf: 'center',
    marginBottom: 20,
    marginTop: 30,
  },
  bkgContainerHome: {
    backgroundColor: 'rgba(23, 45, 89, 0.5);',
    padding: 36,
    maxWidth: 445,
    borderRadius: 15,
    display: 'flex',
  },
  textIput: {
    flex: 1,
    paddingHorizontal: 16,
    color: 'black',
    borderColor: '#fff',
  },
  rowImputs: {
    flex: 1,
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: 20,
    flexWrap: 'wrap',
  },
  columnInput: {
    flex: 1,
  },
  globalContainerForm: {
    flex: 1,
    maxHeight: 'calc(100vh - 160px)',
  },
  globalContainerFormFiche: {
    flex: 1,
    maxHeight: 'calc(100vh - 160px)',
    alignItems: 'center',
  },
  bkgContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingVertical: 40,
    alignSelf: 'center',
    borderRadius: 15,
    width: '100%',
  },
  logoPosition: {
    zIndex: 2,
    position: 'absolute',
    left: 20,
  },
  logoPositionHome: {},
});
